[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade || true",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
