[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ".venv/bin/python -m ensurepip --upgrade || true",
  # se ainda não tiver pip, bootstrap dentro da VENV (sem tocar sistema)
  "(.venv/bin/python -m pip -V >/dev/null 2>&1) || (curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && .venv/bin/python /tmp/get-pip.py)",
  ".venv/bin/python -m pip install --upgrade pip setuptools wheel",
  # 👇 AGORA usamos o requirements.txt da RAIZ
  ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = ".venv/bin/python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
