[phases.setup]
# (nixpkgs: sรณ garantimos python e pip)
nixPkgs = ["python311", "pip"]

[phases.install]
# instalar deps do arquivo da RAIZ
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
# bind em 0.0.0.0 e porta da Railway
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
