[phases.setup]
# adiciona pip/setuptools/wheel nativos do Nix
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
