[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ".venv/bin/python -m ensurepip --upgrade || true",
  ".venv/bin/python -m pip install --upgrade pip setuptools wheel",
  ".venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = ".venv/bin/python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
