[phases.setup]
# Precisamos de python e curl pra baixar o get-pip.py
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py",
  "python /tmp/get-pip.py",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips=*"
