name: smoke-prod

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "requirements.txt"
      - ".github/workflows/smoke.yml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      BASE: ${{ secrets.SMOKE_BASE }}   # ex: https://dils-wallet-production.up.railway.app

    steps:
      - name: Check BASE secret
        run: |
          if [ -z "$BASE" ]; then echo "Missing secret SMOKE_BASE"; exit 1; fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make ephemeral creds
        id: vars
        run: |
          TS=$(date +%s)
          echo "email=smoke${TS}@dilswallet.com" >> $GITHUB_OUTPUT
          echo "pass=smoke-${TS}" >> $GITHUB_OUTPUT

      - name: Register (ignore if not supported or already exists)
        id: register
        run: |
          set -e
          CODE=$(curl -sS -o reg.json -w "%{http_code}" -X POST \
            "$BASE/api/v1/auth/register" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"${{ steps.vars.outputs.email }}\",\"password\":\"${{ steps.vars.outputs.pass }}\"}" || true)
          echo "register_code=$CODE" >> $GITHUB_OUTPUT
          cat reg.json || true

      - name: Login
        id: login
        run: |
          set -e
          CODE=$(curl -sS -o login.json -w "%{http_code}" -X POST \
            "$BASE/api/v1/auth/login" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${{ steps.vars.outputs.email }}&password=${{ steps.vars.outputs.pass }}")
          test "$CODE" -eq 200
          ACCESS=$(jq -r '.access_token' login.json)
          REFRESH=$(jq -r '.refresh_token' login.json)
          if [ -z "$ACCESS" ] || [ -z "$REFRESH" ]; then echo "Missing tokens"; cat login.json; exit 1; fi
          echo "::add-mask::$ACCESS"; echo "::add-mask::$REFRESH"
          echo "access=$ACCESS"  >> $GITHUB_OUTPUT
          echo "refresh=$REFRESH" >> $GITHUB_OUTPUT

      - name: Refresh (JSON body)
        id: refresh
        run: |
          set -e
          CODE=$(curl -sS -o refresh.json -w "%{http_code}" -X POST \
            "$BASE/api/v1/auth/refresh" \
            -H "Content-Type: application/json" \
            -d "{\"refresh_token\":\"${{ steps.login.outputs.refresh }}\"}")
          test "$CODE" -eq 200
          NEW=$(jq -r '.access_token' refresh.json)
          test -n "$NEW"
          echo "new_access=$NEW" >> $GITHUB_OUTPUT

      - name: Balance using new access
        run: |
          set -e
          CODE=$(curl -sS -o bal.json -w "%{http_code}" \
            -H "Authorization: Bearer ${{ steps.refresh.outputs.new_access }}" \
            "$BASE/api/v1/transactions/balance")
          test "$CODE" -eq 200
          cat bal.json
