providers = ["node"]

[variables]
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_FETCH_RETRIES = "5"
NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "120000"

[phases.install]
cmds = [
  "npm ci || npm install --no-audit --no-fund",
  "npm rebuild esbuild || true"
]

[phases.build]
cmds = ["npx vite build --debug"]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"
