providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --no-audit --fund=false"]

# sem build no Railway, vamos enviar o dist pronto
[phases.build]
cmds = []

[start]
cmd = "npm start"
