name: Smoke Prod

on:
  workflow_dispatch:
    inputs:
      FORCE_FAIL_SMOKE_PROD:
        description: Force failure for TG test
        required: false
        default: "1"
        type: choice
        options:
          - "0"
          - "1"
  schedule:
    - cron: "0 */3 * * *"   # a cada 3h

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bash deps (jq, curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run smoke_prod.sh (posts no Slack)
        env:
          SMOKE_BASE: ${{ secrets.SMOKE_BASE }}
          HEALTH_TOKEN: ${{ secrets.HEALTH_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          FORCE_FAIL_SMOKE_PROD: ${{ inputs.FORCE_FAIL_SMOKE_PROD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
        run: |
          chmod +x scripts/smoke_prod.sh
          ./scripts/smoke_prod.sh

      - name: List artifacts dir
        if: always()
        run: |
          echo "PWD=$(pwd)"
          ls -lahR artifacts || true

      - name: Sanity TG env
        if: always()
        run: |
          [ -n "${TG_BOT_TOKEN:-}" ] || { echo "FALTA TG_BOT_TOKEN"; exit 1; }
          [ -n "${TG_CHAT_ID:-}" ]   || { echo "FALTA TG_CHAT_ID"; exit 1; }

      - name: Zip TG artifacts
        if: always()
        run: |
          mkdir -p artifacts/tg/smoke_prod
          zip -j "artifacts/tg/smoke_prod/tg-${{ github.run_id }}.zip" artifacts/tg/smoke_prod/tg.* || true
      - name: Upload TG artifacts (smoke_prod)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tg-debug-smoke-prod
          path: artifacts/tg/smoke_prod/**
          if-no-files-found: error
          retention-days: 7
