name: Smoke Prod
on:
  workflow_dispatch:
    inputs:
      FORCE_FAIL_SMOKE_PROD:
        description: "Force failure for TG test"
        required: false
        default: "0"
  schedule:
    - cron: "0 */3 * * *"   # a cada 6h (ajusta se quiser)

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bash deps (jq, curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run smoke_prod.sh (posts no Slack)
        env:
          # base/health opcionais conforme seu backend
          SMOKE_BASE: ${{ secrets.SMOKE_BASE }}
          HEALTH_TOKEN: ${{ secrets.HEALTH_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          FORCE_FAIL_SMOKE_PROD: ${{ inputs.FORCE_FAIL_SMOKE_PROD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
          # se quiser customizar usuário/valor nesta execução:
          # EMAIL: "smoke@dilswallet.com"
          # PASS: "123456"
          # AMOUNT: "37.50"
          # WITHDRAW: "5.00"
        run: |
          chmod +x scripts/smoke_prod.sh
          ./scripts/smoke_prod.sh
      - name: Upload TG artifacts (smoke_prod)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tg-debug-smoke-prod
          path: artifacts/tg/smoke_prod/*
          if-no-files-found: warn
